#!/usr/bin/env bash

cmd_exists() {
  command -v "$1" >/dev/null 2>&1
}

create_link() {
  ln -fsr "$1" ~
}

pushd "$(dirname "$0")" >/dev/null

if cmd_exists "tmux"; then
  create_link .tmux.conf
fi

if cmd_exists "vim"; then
  create_link .vimrc
fi

popd >/dev/null
