#!/bin/sh

cmd_exists() {
  command -v "$1" >/dev/null 2>&1
}

has_bash() {
  cmd_exists "bash"
}

has_zsh() {
  cmd_exists "zsh"
}

create_link() {
  ln -fsr "$1" "$2"
  echo "Created link for $1 in $2"
}

OLDPWD=$(pwd)
cd "$(dirname "$0")" || exit 1

if has_bash; then
  create_link .bash_aliases ~
  create_link .bash_logout ~
  create_link .bashrc ~
fi

if cmd_exists "fzf"; then
  if has_bash; then
    create_link .fzf.bash ~
  fi
  if has_zsh; then
    create_link .fzf.zsh ~
  fi
fi

if cmd_exists "tmux"; then
  create_link .tmux.conf ~
fi

if cmd_exists "vim"; then
  create_link .vimrc ~
fi

if cmd_exists "yazi"; then
  create_link .config/yazi ~/.config
fi

cd "$OLDPWD" || exit 1
